### ISSUE TITLE
Unable to create belt() with pulley outside the loop.

### ISSUE THREAD

**Issue by lostapathy** [nophead/NopSCADlib#4]
Using this example code, the first pulley in the path should be "outside" the loop of the belt, while the other 3 are inside the belt.

```include <lib.scad>

path = [
  [0, 0, pulley_pr(GT2x20_toothed_idler)],
  [50, 0, pulley_pr(GT2x20_toothed_idler)],
  [-100, 0, pulley_pr(GT2x20_toothed_idler)],
  [-100, 100, pulley_pr(GT2x20_toothed_idler)],
];

belt(type=GT2x6, points=path);
```
The belt path generated around that pulley is:
![image](https://user-images.githubusercontent.com/437470/63401153-ffc5a180-c39b-11e9-8c45-cb85ab20e00a.png)
Which puts it on a completely different path than intended on the machine.

I'm not really sure if this is a supported use case, but it's come up in a project I've started working with.  Thanks!

**Comment by nophead** [comment]
If you want the pulley to be on the outside you need to specify a negative radius. Making that change causes the belt to self intersect, so I also moved it to 5 in the Y direction. You probably would also want to make it a GT2x20_plain_idler because it is running on the back of the belt.

```
path = [
  [0, 5, -pulley_pr(GT2x20_plain_idler)],
  [50, 0, pulley_pr(GT2x20_toothed_idler)],
  [-100, 0, pulley_pr(GT2x20_toothed_idler)],
  [-100, 100, pulley_pr(GT2x20_toothed_idler)],
];
```
![image](https://user-images.githubusercontent.com/566149/63423577-81511a00-c404-11e9-9446-35f96d3b60fe.png)

**Comment by nophead** [comment]
I added an explanatory comment in 7c1ff5ecd59129a1ea63251c76022b9f9d64c858

**Comment by lostapathy** [comment]
thanks!
